/* Saelthyr Dictionary Data — update this file to expand the language */
const SAELTHYR = {
  meta: {
    name: "Saelthyr",
    subtitle: "Dicionário · língua de Preirt",
    description:
      "Língua construída dos demônios de Preirt. Usada no cotidiano e em rituais.",
  },

  grammar: [
    {
      title: "Ordem das palavras",
      body: "A ordem padrão é sujeito → verbo → objeto. Exemplo: Zer gueth sael (Eu guio a alma).",
    },
    {
      title: "Negação",
      body: "Prefixe kel- ao verbo. Exemplo: kel-dyreth (não diga).",
    },
    {
      title: "Possessivo",
      body: "Use va entre o possuidor e a coisa. Exemplo: raith va ryn (o caminho de você / seu caminho).",
    },
    {
      title: "Plural",
      body: "Acrescente o sufixo -im. Exemplo: kylor → kylorim; daemor → daemorim.",
    },
    {
      title: "Perguntas",
      body: "Coloque a partícula kae no FINAL da frase. Exemplo: Ryn essyr kylor kae? (Você é amigo?).",
    },
    {
      title: "Passado (velth)",
      body: "Coloque velth imediatamente antes do verbo. Exemplo: Ryn velth vyth syrel va zer kae? (Você viu meu filho?).",
    },
    {
      title: "Acento tônico",
      body: "O estresse cai geralmente na penúltima sílaba.",
    },
    {
      title: "Pronúncia",
      body: "ae / ey = éi · th = como o th de think (inglês) · yr = ír curto · el final é suave.",
    },
  ],

  customs: [
    {
      title: "Naryth",
      body: "A palavra naryth nunca é falada em público. É o sobrenome verdadeiro — segredo cerimonial.",
    },
    {
      title: "Frases rituais",
      body: "Prefira frases rituais curtas. O discurso cotidiano pode ser mais longo; o sagrado, breve.",
    },
    {
      title: "Banidos",
      body: "Os banidos são frequentemente chamados com draeth kel (lar distante).",
    },
    {
      title: "Resposta às Ordens",
      body: "Ordens se respondem com Eyth (sim / assim seja) ou com silêncio.",
    },
  ],

  categories: [
    { id: "particulas", label: "Partículas" },
    { id: "pessoas", label: "Pessoas" },
    { id: "verbos", label: "Verbos" },
    { id: "tempo_lugar", label: "Tempo & Lugar" },
    { id: "natureza", label: "Natureza" },
    { id: "emocoes", label: "Emoções" },
    { id: "cosmologia", label: "Cosmologia" },
    { id: "racas", label: "Raças" },
    { id: "animais", label: "Animais" },
    { id: "flora", label: "Flora" },
    { id: "criaturas_preirt", label: "Criaturas de Preirt" },
    { id: "frases", label: "Frases" },
  ],

  entries: [
    /* —— Partículas / pronomes —— */
    { saelthyr: "zer", pt: "eu", category: "particulas" },
    { saelthyr: "ryn", pt: "você", category: "particulas" },
    { saelthyr: "velim", pt: "nós", category: "particulas" },
    { saelthyr: "eyth", pt: "sim / assim seja", category: "particulas", notes: "Resposta ritual a Ordens" },
    { saelthyr: "kel", pt: "não / negação", category: "particulas", notes: "Também prefixo kel- em verbos" },
    { saelthyr: "hael", pt: "saudação / olá", category: "particulas" },
    { saelthyr: "faren", pt: "adeus", category: "particulas" },
    { saelthyr: "faren va hushyr", pt: "adeus em paz", category: "particulas", notes: "Fórmula de despedida" },
    { saelthyr: "va", pt: "de (possessivo)", category: "particulas", notes: "Entre possuidor e coisa" },
    { saelthyr: "kae", pt: "partícula interrogativa", category: "particulas", notes: "No final da frase" },
    { saelthyr: "velth", pt: "marcador de passado", category: "particulas", notes: "Antes do verbo: ryn velth vyth = você viu" },
    { saelthyr: "et", pt: "e", category: "particulas" },
    { saelthyr: "sed", pt: "mas / porém", category: "particulas" },
    { saelthyr: "kym", pt: "com", category: "particulas" },
    { saelthyr: "vynel", pt: "sem", category: "particulas" },
    { saelthyr: "sy", pt: "se / caso", category: "particulas" },
    { saelthyr: "qer", pt: "porque / pois", category: "particulas" },
    { saelthyr: "omnis", pt: "todo / tudo", category: "particulas" },
    { saelthyr: "graeth", pt: "obrigado / gratidão", category: "particulas" },
    { saelthyr: "nael", pt: "de nada", category: "particulas" },
    { saelthyr: "shyr", pt: "por favor", category: "particulas" },

    /* —— Pessoas —— */
    { saelthyr: "kylor", pt: "amigo", category: "pessoas" },
    { saelthyr: "kylorim", pt: "amigos", category: "pessoas", notes: "Plural de kylor" },
    { saelthyr: "thrén", pt: "pessoa / alguém", category: "pessoas" },
    { saelthyr: "kael", pt: "criança", category: "pessoas" },
    { saelthyr: "syrel", pt: "filho", category: "pessoas", notes: "kael = criança; syrel = filho" },
    { saelthyr: "saelyra", pt: "filha", category: "pessoas" },
    { saelthyr: "myrath", pt: "precioso / querido", category: "natureza", notes: "Afeto; Hazel essyr myrath syrel va zer" },
    { saelthyr: "velyn", pt: "ancião", category: "pessoas" },
    { saelthyr: "naryth", pt: "sobrenome verdadeiro", category: "pessoas", notes: "Segredo; NUNCA dito em público" },

    /* —— Verbos —— */
    { saelthyr: "essyr", pt: "ser / estar", category: "verbos" },
    { saelthyr: "haveth", pt: "ter", category: "verbos" },
    { saelthyr: "gueth", pt: "guiar", category: "verbos" },
    { saelthyr: "sereth", pt: "proteger", category: "verbos" },
    { saelthyr: "vyth", pt: "ver", category: "verbos" },
    { saelthyr: "vyn", pt: "vir / chegar", category: "verbos" },
    { saelthyr: "ir", pt: "ir", category: "verbos" },
    { saelthyr: "dyreth", pt: "dizer / falar", category: "verbos", notes: "kel-dyreth = não diga" },
    { saelthyr: "auryth", pt: "ouvir", category: "verbos" },
    { saelthyr: "vaelth", pt: "saber / conhecer", category: "verbos" },
    { saelthyr: "volyth", pt: "querer / desejar", category: "verbos" },
    { saelthyr: "poth", pt: "poder (capacidade)", category: "verbos" },
    { saelthyr: "delyth", pt: "dar", category: "verbos" },
    { saelthyr: "gryth", pt: "tomar / pegar", category: "verbos" },
    { saelthyr: "vorath", pt: "comer", category: "verbos" },
    { saelthyr: "sylath", pt: "beber", category: "verbos" },
    { saelthyr: "saureth", pt: "descansar", category: "verbos" },
    { saelthyr: "stryeth", pt: "andar / caminhar", category: "verbos" },
    { saelthyr: "halyth", pt: "esperar", category: "verbos" },
    { saelthyr: "syreth", pt: "ajudar", category: "verbos" },
    { saelthyr: "qyreth", pt: "encontrar", category: "verbos" },
    { saelthyr: "nareth", pt: "perder", category: "verbos" },
    { saelthyr: "threneth", pt: "lembrar", category: "verbos" },
    { saelthyr: "velneth", pt: "esquecer", category: "verbos" },
    { saelthyr: "nyreth", pt: "nascer / surgir", category: "verbos" },
    { saelthyr: "qalreth", pt: "terminar / findar", category: "verbos", notes: "Não necessariamente \"morrer\"" },
    { saelthyr: "thaeleth", pt: "atravessar / transitar", category: "verbos" },

    /* —— Tempo & lugar —— */
    { saelthyr: "chronel", pt: "tempo", category: "tempo_lugar" },
    { saelthyr: "nyth", pt: "agora", category: "tempo_lugar" },
    { saelthyr: "tyrel", pt: "hoje", category: "tempo_lugar" },
    { saelthyr: "thalyn", pt: "amanhã / futuro próximo", category: "tempo_lugar" },
    { saelthyr: "velryn", pt: "ontem / passado próximo", category: "tempo_lugar" },
    { saelthyr: "draeth", pt: "lar / casa", category: "tempo_lugar", notes: "Banidos: draeth kel = lar distante" },
    { saelthyr: "raith", pt: "caminho / trilha", category: "tempo_lugar" },
    { saelthyr: "lok", pt: "lugar", category: "tempo_lugar" },
    { saelthyr: "hir", pt: "aqui", category: "tempo_lugar" },
    { saelthyr: "thor", pt: "lá / ali", category: "tempo_lugar" },
    { saelthyr: "nex", pt: "perto / próximo", category: "tempo_lugar" },
    { saelthyr: "far", pt: "longe", category: "tempo_lugar" },

    /* —— Natureza / coisas —— */
    { saelthyr: "sael", pt: "alma", category: "natureza" },
    { saelthyr: "vyrel", pt: "vida", category: "natureza" },
    { saelthyr: "neth", pt: "morte", category: "natureza" },
    { saelthyr: "hushyr", pt: "silêncio", category: "natureza" },
    { saelthyr: "myrael", pt: "mana", category: "natureza" },
    { saelthyr: "aelyn", pt: "sol", category: "natureza" },
    { saelthyr: "nyrel", pt: "lua", category: "natureza" },
    { saelthyr: "vayr", pt: "água", category: "natureza" },
    { saelthyr: "fyr", pt: "fogo", category: "natureza" },
    { saelthyr: "drael", pt: "terra / solo", category: "natureza" },
    { saelthyr: "caelth", pt: "céu", category: "natureza" },
    { saelthyr: "merath", pt: "comida", category: "natureza" },
    { saelthyr: "sketh", pt: "lâmina", category: "natureza" },
    { saelthyr: "vorel", pt: "roupa", category: "natureza" },
    { saelthyr: "brachim", pt: "braços", category: "natureza" },

    /* —— Emoções —— */
    { saelthyr: "lyrael", pt: "alegria / êxtase", category: "emocoes" },
    { saelthyr: "mireth", pt: "tristeza", category: "emocoes" },
    { saelthyr: "kareth", pt: "medo", category: "emocoes" },
    { saelthyr: "vreth", pt: "raiva", category: "emocoes" },
    { saelthyr: "pael", pt: "paz", category: "emocoes" },
    { saelthyr: "waryn", pt: "cansado", category: "emocoes" },
    { saelthyr: "draen", pt: "ferido", category: "emocoes" },
    { saelthyr: "solryn", pt: "sozinho", category: "emocoes" },

    /* —— Cosmologia —— */
    { saelthyr: "Preirt", pt: "plano dos demônios", category: "cosmologia" },
    { saelthyr: "Aelthyr", pt: "plano dos anjos", category: "cosmologia" },
    { saelthyr: "Aelqor", pt: "Pós-Vida", category: "cosmologia" },
    { saelthyr: "Thael", pt: "o Véu", category: "cosmologia" },
    { saelthyr: "Cor Preirti", pt: "o Coração de Preirt", category: "cosmologia" },
    { saelthyr: "kethar", pt: "Ordem", category: "cosmologia" },
    { saelthyr: "sevath", pt: "pacto", category: "cosmologia" },
    { saelthyr: "Preith", pt: "Pressão de Preirt", category: "cosmologia" },
    { saelthyr: "Draem", pt: "Domínio", category: "cosmologia" },
    { saelthyr: "Rith Vael", pt: "Ritual da Entrega", category: "cosmologia" },
    { saelthyr: "kel-Thael-thaeleth", pt: "não atravessar o Véu", category: "cosmologia", notes: "Ato ritualmente proibido" },

    /* —— Raças —— */
    { saelthyr: "daemor", pt: "demônio", category: "racas" },
    { saelthyr: "daemorim", pt: "demônios", category: "racas", notes: "Plural de daemor" },
    { saelthyr: "aelir", pt: "anjo / ser celestial", category: "racas" },
    { saelthyr: "aelirim", pt: "anjos / seres celestiais", category: "racas", notes: "Plural de aelir" },
    { saelthyr: "elvryn", pt: "elfo", category: "racas" },
    { saelthyr: "elvrynim", pt: "elfos", category: "racas", notes: "Plural de elvryn" },
    { saelthyr: "humryn", pt: "humano", category: "racas" },
    { saelthyr: "humrynim", pt: "humanos", category: "racas", notes: "Plural de humryn" },
    { saelthyr: "saelgueth", pt: "guia de almas", category: "racas" },
    { saelthyr: "saelguethim", pt: "guias de almas", category: "racas", notes: "Plural de saelgueth" },
    { saelthyr: "velgueth", pt: "guardião da vida", category: "racas" },
    { saelthyr: "velguethim", pt: "guardiões da vida", category: "racas", notes: "Plural de velgueth" },

    /* —— Animais —— */
    { saelthyr: "varg", pt: "lobo", category: "animais" },
    { saelthyr: "felra", pt: "gato / felino", category: "animais" },
    { saelthyr: "canth", pt: "cão", category: "animais" },
    { saelthyr: "equir", pt: "cavalo", category: "animais" },
    { saelthyr: "corv", pt: "corvo", category: "animais" },
    { saelthyr: "aquil", pt: "águia", category: "animais" },
    { saelthyr: "serp", pt: "serpente", category: "animais" },
    { saelthyr: "drak", pt: "dragão", category: "animais" },
    { saelthyr: "cerv", pt: "cervo", category: "animais" },
    { saelthyr: "urs", pt: "urso", category: "animais" },
    { saelthyr: "vulp", pt: "raposa", category: "animais" },
    { saelthyr: "avyn", pt: "ave / pássaro", category: "animais" },
    { saelthyr: "pisc", pt: "peixe", category: "animais" },
    { saelthyr: "insecth", pt: "inseto", category: "animais" },
    { saelthyr: "myrth", pt: "rato", category: "animais" },

    /* —— Flora —— */
    { saelthyr: "thryl", pt: "árvore", category: "flora" },
    { saelthyr: "raeliz", pt: "raiz", category: "flora" },
    { saelthyr: "folth", pt: "folha", category: "flora" },
    { saelthyr: "bloomyr", pt: "flor", category: "flora" },
    { saelthyr: "withryn", pt: "flor murcha", category: "flora" },
    { saelthyr: "mossel", pt: "musgo", category: "flora" },
    { saelthyr: "vinex", pt: "cipó / trepadeira", category: "flora" },
    { saelthyr: "seedra", pt: "semente", category: "flora" },
    { saelthyr: "barkh", pt: "casca (de árvore)", category: "flora" },
    { saelthyr: "grovel", pt: "bosque / arvoredo", category: "flora" },
    { saelthyr: "maelth", pt: "campo", category: "flora" },
    { saelthyr: "nythryl", pt: "árvore negra de Preirt", category: "flora" },
    { saelthyr: "saelbloom", pt: "flor-alma", category: "flora" },
    { saelthyr: "silfolth", pt: "folha-do-silêncio", category: "flora" },
    { saelthyr: "myrvinex", pt: "cipó de mana", category: "flora" },
    { saelthyr: "aelroot", pt: "raiz que lembra nomes", category: "flora" },
    { saelthyr: "velmist", pt: "névoa viva", category: "flora" },

    /* —— Criaturas de Preirt —— */
    { saelthyr: "saelcanth", pt: "cão-guia", category: "criaturas_preirt" },
    { saelthyr: "thaelwyn", pt: "asa-do-véu", category: "criaturas_preirt" },
    { saelthyr: "raelspyr", pt: "espectro-de-raiz", category: "criaturas_preirt" },
    { saelthyr: "silvryn", pt: "raposa-do-silêncio", category: "criaturas_preirt" },
    { saelthyr: "saelcerv", pt: "cervo-eco", category: "criaturas_preirt" },
    { saelthyr: "myraelthyr", pt: "aranha-de-mana", category: "criaturas_preirt" },
    { saelthyr: "nythrael", pt: "mariposa-noturna", category: "criaturas_preirt" },
    { saelthyr: "thaeleer", pt: "guardião do Véu", category: "criaturas_preirt" },


    /* —— Fantasia medieval —— */
    { saelthyr: "cruorath", pt: "sangue", category: "natureza" },
    { saelthyr: "nythel", pt: "noite", category: "tempo_lugar" },
    { saelthyr: "aeldyn", pt: "dia (período claro)", category: "tempo_lugar", notes: "tyrel = hoje; aeldyn = o dia" },
    { saelthyr: "skeldra", pt: "espada", category: "natureza" },
    { saelthyr: "speirath", pt: "lança", category: "natureza" },
    { saelthyr: "scythel", pt: "escudo", category: "natureza" },
    { saelthyr: "koryn", pt: "elmo", category: "natureza" },
    { saelthyr: "armyth", pt: "armadura", category: "natureza" },
    { saelthyr: "quarelth", pt: "arco", category: "natureza" },
    { saelthyr: "lyrath", pt: "flecha", category: "natureza" },
    { saelthyr: "vyrsketh", pt: "adaga", category: "natureza" },
    { saelthyr: "warath", pt: "guerra / batalha", category: "natureza" },
    { saelthyr: "castrel", pt: "castelo", category: "tempo_lugar" },
    { saelthyr: "towryn", pt: "torre", category: "tempo_lugar" },
    { saelthyr: "villath", pt: "vila", category: "tempo_lugar" },
    { saelthyr: "rexath", pt: "rei", category: "pessoas" },
    { saelthyr: "regalyra", pt: "rainha", category: "pessoas" },
    { saelthyr: "voryn", pt: "cavaleiro", category: "pessoas" },
    { saelthyr: "myraelor", pt: "mago / feiticeiro", category: "pessoas" },
    { saelthyr: "nythwyn", pt: "bruxa / feiticeira", category: "pessoas" },
    { saelthyr: "haelmir", pt: "sacerdote", category: "pessoas" },
    { saelthyr: "haeldom", pt: "templo", category: "tempo_lugar" },
    { saelthyr: "auryn", pt: "ouro", category: "natureza" },
    { saelthyr: "argelyr", pt: "prata", category: "natureza" },
    { saelthyr: "ferath", pt: "ferro", category: "natureza" },
    { saelthyr: "drakfyr", pt: "fogo de dragão", category: "natureza" },
    { saelthyr: "myrket", pt: "feitiço", category: "natureza" },
    { saelthyr: "runeth", pt: "runa", category: "natureza" },
    { saelthyr: "thaelpor", pt: "portal", category: "cosmologia" },
    { saelthyr: "corwyn", pt: "coroa", category: "natureza" },
    { saelthyr: "banthyr", pt: "estandarte", category: "natureza" },
    { saelthyr: "warquil", pt: "montaria de guerra", category: "animais" },
    { saelthyr: "depthyr", pt: "masmorra", category: "tempo_lugar" },
    { saelthyr: "pyrael", pt: "chama ritual", category: "natureza", notes: "fyr = fogo; pyrael = chama mágica/ritual" },
    { saelthyr: "thurmyn", pt: "tempestade", category: "natureza" },
    { saelthyr: "nyreluor", pt: "luar", category: "natureza" },
    { saelthyr: "nethyr", pt: "sombra", category: "natureza" },
    { saelthyr: "aellyr", pt: "luz", category: "natureza" },
    { saelthyr: "smelthyr", pt: "forja", category: "tempo_lugar" },
    { saelthyr: "haeldryn", pt: "taverna", category: "tempo_lugar" },
    { saelthyr: "raithor", pt: "estrada", category: "tempo_lugar" },
    { saelthyr: "spanyl", pt: "ponte", category: "tempo_lugar" },
    { saelthyr: "rexdom", pt: "reino", category: "tempo_lugar" },
    { saelthyr: "Zer haveth skeldra.", pt: "Eu tenho uma espada.", category: "frases" },
    { saelthyr: "Nythel essyr hir.", pt: "A noite está aqui.", category: "frases" },
    { saelthyr: "Cruorath va daemor.", pt: "Sangue de demônio.", category: "frases" },
    { saelthyr: "Fyr et skeldra.", pt: "Fogo e espada.", category: "frases" },

    /* —— Frases —— */
    { saelthyr: "Hael, kylor.", pt: "Olá, amigo.", category: "frases" },
    { saelthyr: "Zer gueth sael.", pt: "Eu guio a alma.", category: "frases" },
    { saelthyr: "Zer sereth raith va ryn.", pt: "Eu protejo o seu caminho.", category: "frases" },
    { saelthyr: "Vyrel Aelthyr; neth Preirt.", pt: "Vida em Aelthyr; morte em Preirt.", category: "frases" },
    {
      saelthyr: "Omnis sael nyreth Aelthyr, qalreth brachim Preirt.",
      pt: "Toda alma nasce sob Aelthyr e termina nos braços de Preirt.",
      category: "frases",
    },
    { saelthyr: "Naryth kel-dyreth.", pt: "Não diga o sobrenome verdadeiro.", category: "frases", notes: "Nunca pronunciar naryth em público" },
    { saelthyr: "Preirt essyr hushyr.", pt: "Preirt está em silêncio.", category: "frases" },
    { saelthyr: "Ryn essyr kylor kae?", pt: "Você é amigo?", category: "frases" },
    { saelthyr: "Zer volyth merath.", pt: "Eu quero comida.", category: "frases" },
    { saelthyr: "Ryn poth syreth zer kae?", pt: "Você pode me ajudar?", category: "frases" },
    { saelthyr: "Zer vaelth kel.", pt: "Eu não sei.", category: "frases" },
    { saelthyr: "Graeth, kylor.", pt: "Obrigado, amigo.", category: "frases" },
    { saelthyr: "Faren va hushyr.", pt: "Adeus em paz.", category: "frases" },
    { saelthyr: "Zer essyr daemor.", pt: "Eu sou um demônio.", category: "frases" },
    { saelthyr: "Nythryl essyr nex Cor Preirti.", pt: "A árvore negra está perto do Coração de Preirt.", category: "frases" },
    { saelthyr: "Ryn velth vyth syrel va zer kae?", pt: "Você viu meu filho?", category: "frases", notes: "velth = passado antes do verbo" },
  ],
};
