/* Saelthyr Dictionary Data — update this file to expand the language */
const SAELTHYR = {
  meta: {
    name: "Saelthyr",
    subtitle: "Dicionário · língua de Preirt",
    description:
      "Língua construída dos demônios de Preirt. Baseada vagamente no latim, mas sem cognatos óbvios. Usada no cotidiano e em rituais do lore Zeraph/Preirt.",
  },

  grammar: [
    {
      title: "Ordem das palavras",
      body: "A ordem padrão é sujeito → verbo → objeto. Exemplo: Zer gueth sael (Eu guio a alma).",
    },
    {
      title: "Negação",
      body: "Prefixe kel- ao verbo. Exemplo: kel-dyreth (não diga).",
    },
    {
      title: "Possessivo",
      body: "Use va entre o possuidor e a coisa. Exemplo: raith va ryn (o caminho de você / seu caminho).",
    },
    {
      title: "Plural",
      body: "Acrescente o sufixo -im. Exemplo: kylor → kylorim; daemor → daemorim.",
    },
    {
      title: "Perguntas",
      body: "Coloque a partícula kae no FINAL da frase. Exemplo: Ryn essyr kylor kae? (Você é amigo?).",
    },
    {
      title: "Futuro, lugar e pessoa",
      body: "nelth antes do verbo marca o futuro (zer nelth ir = eu irei). yn = em; soveth = sobre; vraen = antes; ostel = depois. ael = ele/ela; aelim = eles. jael = já; athen = ainda; naeth = nunca. qed sy = mesmo se.",
    },
    {
      title: "Que (qyr)",
      body: "qyr liga a oração. Exemplo: Thraelim qyr velth kel-essyr Preirt kel-haveth dyreth. (Coisas que não existiam em Preirt não têm palavra.) qen = para que; qel = quando; qed = embora.",
    },
    {
      title: "Passado (velth)",
      body: "Coloque velth imediatamente antes do verbo. Exemplo: Ryn velth vyth syrel va zer kae? (Você viu meu filho?).",
    },
    {
      title: "Acento tônico",
      body: "O estresse cai geralmente na penúltima sílaba.",
    },
    {
      title: "Pronúncia",
      body: "ae / ey = éi · th = como o th de think (inglês) · yr = ír curto · el final é suave.",
    },
  ],

  customs: [
    {
      title: "Naryth",
      body: "A palavra naryth nunca é falada em público. É o sobrenome verdadeiro — segredo cerimonial.",
    },
    {
      title: "Frases rituais",
      body: "Prefira frases rituais curtas. O discurso cotidiano pode ser mais longo; o sagrado, breve.",
    },
    {
      title: "Banidos",
      body: "Os banidos são frequentemente chamados com draeth kel (lar distante).",
    },
    {
      title: "Resposta às Ordens",
      body: "Ordens se respondem com Eyth (sim / assim seja) ou com silêncio.",
    },
  ],

  categories: [
    { id: "particulas", label: "Partículas" },
    { id: "tecnologia", label: "Tecnologia" },
    { id: "calendario", label: "Calendário & Números" },
    { id: "pessoas", label: "Pessoas" },
    { id: "verbos", label: "Verbos" },
    { id: "tempo_lugar", label: "Tempo & Lugar" },
    { id: "natureza", label: "Natureza" },
    { id: "emocoes", label: "Emoções" },
    { id: "cosmologia", label: "Cosmologia" },
    { id: "racas", label: "Raças" },
    { id: "animais", label: "Animais" },
    { id: "flora", label: "Flora" },
    { id: "criaturas_preirt", label: "Criaturas de Preirt" },
    { id: "frases", label: "Frases" },
  ],

  entries: [
    /* —— Partículas / pronomes —— */
    { saelthyr: "zer", pt: "eu", category: "particulas" },
    { saelthyr: "ryn", pt: "você", category: "particulas" },
    { saelthyr: "zerim", pt: "nós", category: "particulas", notes: "substitui velim" },
    { saelthyr: "rynim", pt: "vocês", category: "particulas" },
    { saelthyr: "eyth", pt: "sim / assim seja", category: "particulas", notes: "Resposta ritual a Ordens" },
    { saelthyr: "kel", pt: "não / negação", category: "particulas", notes: "Também prefixo kel- em verbos" },
    { saelthyr: "hael", pt: "saudação / olá", category: "particulas" },
    { saelthyr: "faren", pt: "adeus", category: "particulas" },
    { saelthyr: "faren va hushyr", pt: "adeus em paz", category: "particulas", notes: "Fórmula de despedida" },
    { saelthyr: "va", pt: "de (possessivo)", category: "particulas", notes: "Entre possuidor e coisa" },
    { saelthyr: "kae", pt: "partícula interrogativa", category: "particulas", notes: "No final da frase" },
    { saelthyr: "velth", pt: "marcador de passado", category: "particulas", notes: "Antes do verbo: ryn velth vyth = você viu" },
    { saelthyr: "et", pt: "e", category: "particulas" },
    { saelthyr: "sed", pt: "mas / porém", category: "particulas" },
    { saelthyr: "kym", pt: "com", category: "particulas" },
    { saelthyr: "vynel", pt: "sem", category: "particulas" },
    { saelthyr: "sy", pt: "se / caso", category: "particulas" },
    { saelthyr: "qer", pt: "porque / pois", category: "particulas" },
    { saelthyr: "qyr", pt: "que", category: "particulas", notes: "Liga orações: thraelim qyr velth kel-essyr Preirt" },
    { saelthyr: "qen", pt: "para que", category: "particulas" },
    { saelthyr: "qel", pt: "quando", category: "particulas" },
    { saelthyr: "qed", pt: "embora / mesmo que", category: "particulas", notes: "qed sy = mesmo se" },
    { saelthyr: "ael", pt: "ele / ela", category: "particulas", notes: "Também objeto: dyreth ael" },
    { saelthyr: "aelim", pt: "eles / elas", category: "particulas" },
    { saelthyr: "yn", pt: "em / dentro de", category: "particulas" },
    { saelthyr: "soveth", pt: "sobre / a respeito de", category: "particulas" },
    { saelthyr: "vraen", pt: "antes", category: "particulas" },
    { saelthyr: "ostel", pt: "depois", category: "particulas" },
    { saelthyr: "nelth", pt: "marcador de futuro", category: "particulas", notes: "Antes do verbo: zer nelth ir = eu irei" },
    { saelthyr: "jael", pt: "já", category: "particulas" },
    { saelthyr: "athen", pt: "ainda", category: "particulas" },
    { saelthyr: "naeth", pt: "nunca", category: "particulas" },
    { saelthyr: "omnis", pt: "todo / tudo", category: "particulas" },
    { saelthyr: "graeth", pt: "obrigado / gratidão", category: "particulas" },
    { saelthyr: "nael", pt: "de nada", category: "particulas" },
    { saelthyr: "shyr", pt: "por favor", category: "particulas" },

    /* —— Pessoas —— */
    { saelthyr: "kylor", pt: "amigo", category: "pessoas" },
    { saelthyr: "kylorim", pt: "amigos", category: "pessoas", notes: "Plural de kylor" },
    { saelthyr: "thrén", pt: "pessoa / alguém", category: "pessoas" },
    { saelthyr: "kael", pt: "criança", category: "pessoas" },
    { saelthyr: "thrael", pt: "coisa", category: "natureza", notes: "Plural thraelim" },
    { saelthyr: "orvyn", pt: "mundo", category: "tempo_lugar", notes: "lok = lugar; orvyn = o mundo" },
    { saelthyr: "syrel", pt: "filho", category: "pessoas", notes: "kael = criança; syrel = filho" },
    { saelthyr: "saelyra", pt: "filha", category: "pessoas" },
    { saelthyr: "myrath", pt: "precioso / querido", category: "natureza", notes: "Afeto; Hazel essyr myrath syrel va zer" },
    { saelthyr: "velyn", pt: "ancião", category: "pessoas" },
    { saelthyr: "naryth", pt: "sobrenome verdadeiro", category: "pessoas", notes: "Segredo; NUNCA dito em público" },

    /* —— Verbos —— */
    { saelthyr: "essyr", pt: "ser / estar", category: "verbos" },
    { saelthyr: "haveth", pt: "ter", category: "verbos" },
    { saelthyr: "gueth", pt: "guiar", category: "verbos" },
    { saelthyr: "sereth", pt: "proteger", category: "verbos" },
    { saelthyr: "vyth", pt: "ver", category: "verbos" },
    { saelthyr: "vyn", pt: "vir / chegar", category: "verbos" },
    { saelthyr: "ir", pt: "ir", category: "verbos" },
    { saelthyr: "dyreth", pt: "dizer / falar", category: "verbos", notes: "kel-dyreth = não diga" },
    { saelthyr: "dyrael", pt: "tradução", category: "natureza", notes: "dyreth = falar; dyrael = a tradução da palavra" },
    { saelthyr: "dyraelth", pt: "traduzir", category: "verbos" },
    { saelthyr: "auryth", pt: "ouvir", category: "verbos" },
    { saelthyr: "vaelth", pt: "saber / conhecer", category: "verbos" },
    { saelthyr: "volyth", pt: "querer / desejar", category: "verbos" },
    { saelthyr: "poth", pt: "poder (capacidade)", category: "verbos" },
    { saelthyr: "delyth", pt: "dar", category: "verbos" },
    { saelthyr: "gryth", pt: "tomar / pegar", category: "verbos" },
    { saelthyr: "vorath", pt: "comer", category: "verbos" },
    { saelthyr: "sylath", pt: "beber", category: "verbos" },
    { saelthyr: "saureth", pt: "descansar", category: "verbos" },
    { saelthyr: "stryeth", pt: "andar / caminhar", category: "verbos" },
    { saelthyr: "halyth", pt: "esperar", category: "verbos" },
    { saelthyr: "syreth", pt: "ajudar", category: "verbos" },
    { saelthyr: "qyreth", pt: "encontrar", category: "verbos" },
    { saelthyr: "nareth", pt: "perder", category: "verbos" },
    { saelthyr: "threneth", pt: "lembrar", category: "verbos" },
    { saelthyr: "velneth", pt: "esquecer", category: "verbos" },
    { saelthyr: "nyreth", pt: "nascer / surgir", category: "verbos" },
    { saelthyr: "qalreth", pt: "terminar / findar", category: "verbos", notes: "Não necessariamente \"morrer\"" },
    { saelthyr: "thaeleth", pt: "atravessar / transitar", category: "verbos" },

    /* —— Tempo & lugar —— */
    { saelthyr: "chronel", pt: "tempo", category: "tempo_lugar" },
    { saelthyr: "nyth", pt: "agora", category: "tempo_lugar" },
    { saelthyr: "tyrel", pt: "hoje", category: "tempo_lugar" },
    { saelthyr: "thalyn", pt: "amanhã / futuro próximo", category: "tempo_lugar" },
    { saelthyr: "velryn", pt: "ontem / passado próximo", category: "tempo_lugar" },
    { saelthyr: "draeth", pt: "lar / casa", category: "tempo_lugar", notes: "Banidos: draeth kel = lar distante" },
    { saelthyr: "raith", pt: "caminho / trilha", category: "tempo_lugar" },
    { saelthyr: "lok", pt: "lugar", category: "tempo_lugar" },
    { saelthyr: "hir", pt: "aqui", category: "tempo_lugar" },
    { saelthyr: "thor", pt: "lá / ali", category: "tempo_lugar" },
    { saelthyr: "nex", pt: "perto / próximo", category: "tempo_lugar" },
    { saelthyr: "far", pt: "longe", category: "tempo_lugar" },

    /* —— Natureza / coisas —— */
    { saelthyr: "sael", pt: "alma", category: "natureza" },
    { saelthyr: "vyrel", pt: "vida", category: "natureza" },
    { saelthyr: "neth", pt: "morte", category: "natureza" },
    { saelthyr: "hushyr", pt: "silêncio", category: "natureza" },
    { saelthyr: "myrael", pt: "mana", category: "natureza" },
    { saelthyr: "aelyn", pt: "sol", category: "natureza" },
    { saelthyr: "nyrel", pt: "lua", category: "natureza" },
    { saelthyr: "vayr", pt: "água", category: "natureza" },
    { saelthyr: "fyr", pt: "fogo", category: "natureza" },
    { saelthyr: "drael", pt: "terra / solo", category: "natureza" },
    { saelthyr: "caelth", pt: "céu", category: "natureza" },
    { saelthyr: "merath", pt: "comida", category: "natureza" },
    { saelthyr: "sketh", pt: "lâmina", category: "natureza" },
    { saelthyr: "vorel", pt: "roupa", category: "natureza" },
    { saelthyr: "brachim", pt: "braços", category: "natureza" },

    /* —— Emoções —— */
    { saelthyr: "lyrael", pt: "alegria / êxtase", category: "emocoes" },
    { saelthyr: "mireth", pt: "tristeza", category: "emocoes" },
    { saelthyr: "kareth", pt: "medo", category: "emocoes" },
    { saelthyr: "vreth", pt: "raiva", category: "emocoes" },
    { saelthyr: "pael", pt: "paz", category: "emocoes" },
    { saelthyr: "waryn", pt: "cansado", category: "emocoes" },
    { saelthyr: "draen", pt: "ferido", category: "emocoes" },
    { saelthyr: "solryn", pt: "sozinho", category: "emocoes" },

    /* —— Cosmologia —— */
    { saelthyr: "Preirt", pt: "plano dos demônios", category: "cosmologia" },
    { saelthyr: "Aelthyr", pt: "plano dos anjos", category: "cosmologia" },
    { saelthyr: "Aelqor", pt: "Pós-Vida", category: "cosmologia" },
    { saelthyr: "Thael", pt: "o Véu", category: "cosmologia" },
    { saelthyr: "Cor Preirti", pt: "o Coração de Preirt", category: "cosmologia" },
    { saelthyr: "kethar", pt: "Ordem", category: "cosmologia" },
    { saelthyr: "sevath", pt: "pacto", category: "cosmologia" },
    { saelthyr: "Preith", pt: "Pressão de Preirt", category: "cosmologia" },
    { saelthyr: "Draem", pt: "Domínio", category: "cosmologia" },
    { saelthyr: "Rith Vael", pt: "Ritual da Entrega", category: "cosmologia" },
    { saelthyr: "kel-Thael-thaeleth", pt: "não atravessar o Véu", category: "cosmologia", notes: "Ato ritualmente proibido" },

    /* —— Raças —— */
    { saelthyr: "daemor", pt: "demônio", category: "racas" },
    { saelthyr: "daemorim", pt: "demônios", category: "racas", notes: "Plural de daemor" },
    { saelthyr: "aelir", pt: "anjo / ser celestial", category: "racas" },
    { saelthyr: "aelirim", pt: "anjos / seres celestiais", category: "racas", notes: "Plural de aelir" },
    { saelthyr: "elvryn", pt: "elfo", category: "racas" },
    { saelthyr: "elvrynim", pt: "elfos", category: "racas", notes: "Plural de elvryn" },
    { saelthyr: "humryn", pt: "humano", category: "racas" },
    { saelthyr: "humrynim", pt: "humanos", category: "racas", notes: "Plural de humryn" },
    { saelthyr: "saelgueth", pt: "guia de almas", category: "racas" },
    { saelthyr: "saelguethim", pt: "guias de almas", category: "racas", notes: "Plural de saelgueth" },
    { saelthyr: "velgueth", pt: "guardião da vida", category: "racas" },
    { saelthyr: "velguethim", pt: "guardiões da vida", category: "racas", notes: "Plural de velgueth" },

    /* —— Animais —— */
    { saelthyr: "varg", pt: "lobo", category: "animais" },
    { saelthyr: "felra", pt: "gato / felino", category: "animais" },
    { saelthyr: "canth", pt: "cão", category: "animais" },
    { saelthyr: "equir", pt: "cavalo", category: "animais" },
    { saelthyr: "corv", pt: "corvo", category: "animais" },
    { saelthyr: "aquil", pt: "águia", category: "animais" },
    { saelthyr: "serp", pt: "serpente", category: "animais" },
    { saelthyr: "drak", pt: "dragão", category: "animais" },
    { saelthyr: "cerv", pt: "cervo", category: "animais" },
    { saelthyr: "urs", pt: "urso", category: "animais" },
    { saelthyr: "vulp", pt: "raposa", category: "animais" },
    { saelthyr: "avyn", pt: "ave / pássaro", category: "animais" },
    { saelthyr: "pisc", pt: "peixe", category: "animais" },
    { saelthyr: "insecth", pt: "inseto", category: "animais" },
    { saelthyr: "myrth", pt: "rato", category: "animais" },

    /* —— Flora —— */
    { saelthyr: "thryl", pt: "árvore", category: "flora" },
    { saelthyr: "raeliz", pt: "raiz", category: "flora" },
    { saelthyr: "folth", pt: "folha", category: "flora" },
    { saelthyr: "bloomyr", pt: "flor", category: "flora" },
    { saelthyr: "withryn", pt: "flor murcha", category: "flora" },
    { saelthyr: "mossel", pt: "musgo", category: "flora" },
    { saelthyr: "vinex", pt: "cipó / trepadeira", category: "flora" },
    { saelthyr: "seedra", pt: "semente", category: "flora" },
    { saelthyr: "barkh", pt: "casca (de árvore)", category: "flora" },
    { saelthyr: "grovel", pt: "bosque / arvoredo", category: "flora" },
    { saelthyr: "maelth", pt: "campo", category: "flora" },
    { saelthyr: "nythryl", pt: "árvore negra de Preirt", category: "flora" },
    { saelthyr: "saelbloom", pt: "flor-alma", category: "flora" },
    { saelthyr: "silfolth", pt: "folha-do-silêncio", category: "flora" },
    { saelthyr: "myrvinex", pt: "cipó de mana", category: "flora" },
    { saelthyr: "aelroot", pt: "raiz que lembra nomes", category: "flora" },
    { saelthyr: "velmist", pt: "névoa viva", category: "flora" },

    /* —— Criaturas de Preirt —— */
    { saelthyr: "saelcanth", pt: "cão-guia", category: "criaturas_preirt" },
    { saelthyr: "thaelwyn", pt: "asa-do-véu", category: "criaturas_preirt" },
    { saelthyr: "raelspyr", pt: "espectro-de-raiz", category: "criaturas_preirt" },
    { saelthyr: "silvryn", pt: "raposa-do-silêncio", category: "criaturas_preirt" },
    { saelthyr: "saelcerv", pt: "cervo-eco", category: "criaturas_preirt" },
    { saelthyr: "myraelthyr", pt: "aranha-de-mana", category: "criaturas_preirt" },
    { saelthyr: "nythrael", pt: "mariposa-noturna", category: "criaturas_preirt" },
    { saelthyr: "thaeleer", pt: "guardião do Véu", category: "criaturas_preirt" },


    /* —— Fantasia medieval —— */
    { saelthyr: "cruorath", pt: "sangue", category: "natureza" },
    { saelthyr: "nythel", pt: "noite", category: "tempo_lugar" },
    { saelthyr: "aeldyn", pt: "dia (período claro)", category: "tempo_lugar", notes: "tyrel = hoje; aeldyn = o dia" },
    { saelthyr: "skeldra", pt: "espada", category: "natureza" },
    { saelthyr: "speirath", pt: "lança", category: "natureza" },
    { saelthyr: "scythel", pt: "escudo", category: "natureza" },
    { saelthyr: "koryn", pt: "elmo", category: "natureza" },
    { saelthyr: "armyth", pt: "armadura", category: "natureza" },
    { saelthyr: "quarelth", pt: "arco", category: "natureza" },
    { saelthyr: "lyrath", pt: "flecha", category: "natureza" },
    { saelthyr: "vyrsketh", pt: "adaga", category: "natureza" },
    { saelthyr: "warath", pt: "guerra / batalha", category: "natureza" },
    { saelthyr: "castrel", pt: "castelo", category: "tempo_lugar" },
    { saelthyr: "towryn", pt: "torre", category: "tempo_lugar" },
    { saelthyr: "villath", pt: "vila", category: "tempo_lugar" },
    { saelthyr: "rexath", pt: "rei", category: "pessoas" },
    { saelthyr: "regalyra", pt: "rainha", category: "pessoas" },
    { saelthyr: "voryn", pt: "cavaleiro", category: "pessoas" },
    { saelthyr: "myraelor", pt: "mago / feiticeiro", category: "pessoas" },
    { saelthyr: "nythwyn", pt: "bruxa / feiticeira", category: "pessoas" },
    { saelthyr: "haelmir", pt: "sacerdote", category: "pessoas" },
    { saelthyr: "haeldom", pt: "templo", category: "tempo_lugar" },
    { saelthyr: "auryn", pt: "ouro", category: "natureza" },
    { saelthyr: "argelyr", pt: "prata", category: "natureza" },
    { saelthyr: "ferath", pt: "ferro", category: "natureza" },
    { saelthyr: "drakfyr", pt: "fogo de dragão", category: "natureza" },
    { saelthyr: "myrket", pt: "feitiço", category: "natureza" },
    { saelthyr: "runeth", pt: "runa", category: "natureza" },
    { saelthyr: "thaelpor", pt: "portal", category: "cosmologia" },
    { saelthyr: "corwyn", pt: "coroa", category: "natureza" },
    { saelthyr: "banthyr", pt: "estandarte", category: "natureza" },
    { saelthyr: "warquil", pt: "montaria de guerra", category: "animais" },
    { saelthyr: "depthyr", pt: "masmorra", category: "tempo_lugar" },
    { saelthyr: "pyrael", pt: "chama ritual", category: "natureza", notes: "fyr = fogo; pyrael = chama mágica/ritual" },
    { saelthyr: "thurmyn", pt: "tempestade", category: "natureza" },
    { saelthyr: "nyreluor", pt: "luar", category: "natureza" },
    { saelthyr: "nethyr", pt: "sombra", category: "natureza" },
    { saelthyr: "aellyr", pt: "luz", category: "natureza" },
    { saelthyr: "smelthyr", pt: "forja", category: "tempo_lugar" },
    { saelthyr: "haeldryn", pt: "taverna", category: "tempo_lugar" },
    { saelthyr: "raithor", pt: "estrada", category: "tempo_lugar" },
    { saelthyr: "spanyl", pt: "ponte", category: "tempo_lugar" },
    { saelthyr: "rexdom", pt: "reino", category: "tempo_lugar" },
    /* —— Tecnologia, calendário e números (UI Cruorthyr) —— */
    { saelthyr: "haelth", pt: "prazer / alegria", category: "emocoes" },
    { saelthyr: "naereth", pt: "conhecer / encontrar (pessoa)", category: "verbos" },
    { saelthyr: "mael", pt: "o quê", category: "particulas", notes: "Mael kae?" },
    { saelthyr: "ruvel", pt: "eco", category: "natureza" },
    { saelthyr: "ruveth", pt: "ecoar / reproduzir (mídia)", category: "verbos" },
    { saelthyr: "ruvelth", pt: "ressonância", category: "natureza" },
    { saelthyr: "saelruvel", pt: "sinal", category: "tecnologia", notes: "sael + ruvel = eco de alma" },
    { saelthyr: "kaeryn", pt: "elo / vínculo / conexão", category: "tecnologia" },
    { saelthyr: "kaereth", pt: "conectar / parear", category: "verbos", notes: "de kaeryn" },
    { saelthyr: "kaerorvyn", pt: "rede", category: "tecnologia", notes: "kaeryn + orvyn = mundo de elos" },
    { saelthyr: "caelkaeryn", pt: "wifi", category: "tecnologia", notes: "caelth + kaeryn = elo do céu" },
    { saelthyr: "nexkaeryn", pt: "bluetooth (elo de perto)", category: "tecnologia", notes: "nex (perto) + kaeryn (elo)" },
    { saelthyr: "caelruvel", pt: "rádio", category: "tecnologia", notes: "caelth + ruvel = eco do céu" },
    { saelthyr: "thaelruvel", pt: "transmissão / live", category: "tecnologia", notes: "thael(eth) + ruvel; live = thaelruvel vyrel" },
    { saelthyr: "aurael", pt: "áudio", category: "tecnologia", notes: "de auryth" },
    { saelthyr: "runethyr", pt: "sistema / tecnologia", category: "tecnologia", notes: "de runeth; runeth = dispositivo no contexto técnico" },
    { saelthyr: "lorvael", pt: "arquivo / registro", category: "tecnologia" },
    { saelthyr: "dyrethal", pt: "relatório / relato", category: "tecnologia", notes: "de dyreth; dyrethim = dados" },
    { saelthyr: "kaeldyr", pt: "comando / ordem", category: "tecnologia" },
    { saelthyr: "baeryn", pt: "portadora", category: "tecnologia" },
    { saelthyr: "myraelkor", pt: "célula / bateria", category: "tecnologia", notes: "myrael + cor; myrael = carga" },
    { saelthyr: "faeth", pt: "modo", category: "tecnologia" },
    { saelthyr: "thaven", pt: "recurso", category: "tecnologia" },
    { saelthyr: "halven", pt: "reserva", category: "tecnologia" },
    { saelthyr: "vaelkyr", pt: "jogo", category: "tecnologia" },
    { saelthyr: "aelyth", pt: "canção / faixa", category: "tecnologia" },
    { saelthyr: "nyrael", pt: "evento", category: "tecnologia", notes: "de nyreth" },
    { saelthyr: "draenth", pt: "erro / falha", category: "tecnologia", notes: "de draen" },
    { saelthyr: "ostnyreth", pt: "reiniciar / renascer", category: "verbos", notes: "ostel + nyreth" },
    { saelthyr: "maereth", pt: "restaurar / voltar", category: "verbos" },
    { saelthyr: "korveth", pt: "prender / travar", category: "verbos" },
    { saelthyr: "thumeth", pt: "pulsar", category: "verbos" },
    { saelthyr: "skethyr", pt: "cortar / fragmentar", category: "verbos", notes: "de sketh" },
    { saelthyr: "draeleth", pt: "estabelecer / assentar", category: "verbos", notes: "de drael" },
    { saelthyr: "porveth", pt: "abrir", category: "verbos", notes: "kelporveth = fechar" },
    { saelthyr: "dryveth", pt: "cair", category: "verbos" },
    { saelthyr: "vaereth", pt: "começar", category: "verbos" },
    { saelthyr: "aelveth", pt: "despertar / acordar", category: "verbos" },
    { saelthyr: "thaenyr", pt: "novo", category: "particulas" },
    { saelthyr: "thyrn", pt: "cheio / saturado", category: "particulas" },
    { saelthyr: "lyn", pt: "pouco / baixo", category: "particulas" },
    { saelthyr: "syth", pt: "rápido", category: "particulas" },
    { saelthyr: "kyrel", pt: "ciclo", category: "tempo_lugar" },
    { saelthyr: "thuvel", pt: "nuvem", category: "natureza" },
    { saelthyr: "haevyr", pt: "neblina", category: "natureza" },
    { saelthyr: "skaelyr", pt: "neve", category: "natureza" },
    { saelthyr: "aenyr", pt: "unidade", category: "calendario", notes: "de aen" },
    { saelthyr: "vaen", pt: "0", category: "calendario", notes: "numeral" },
    { saelthyr: "aen", pt: "1", category: "calendario", notes: "numeral" },
    { saelthyr: "dwyr", pt: "2", category: "calendario", notes: "numeral" },
    { saelthyr: "thryn", pt: "3", category: "calendario", notes: "numeral" },
    { saelthyr: "kaeth", pt: "4", category: "calendario", notes: "numeral" },
    { saelthyr: "pyrn", pt: "5", category: "calendario", notes: "numeral" },
    { saelthyr: "hesk", pt: "6", category: "calendario", notes: "numeral" },
    { saelthyr: "vyl", pt: "7", category: "calendario", notes: "numeral" },
    { saelthyr: "oryn", pt: "8", category: "calendario", notes: "numeral" },
    { saelthyr: "nyrr", pt: "9", category: "calendario", notes: "numeral" },
    { saelthyr: "aelyndyn", pt: "domingo", category: "calendario", notes: "sufixo -dyn (de aeldyn); abrev. ÆLY" },
    { saelthyr: "nyreldyn", pt: "segunda-feira", category: "calendario", notes: "sufixo -dyn (de aeldyn); abrev. NYR" },
    { saelthyr: "fyrdyn", pt: "terça-feira", category: "calendario", notes: "sufixo -dyn (de aeldyn); abrev. FYR" },
    { saelthyr: "vayrdyn", pt: "quarta-feira", category: "calendario", notes: "sufixo -dyn (de aeldyn); abrev. VAY" },
    { saelthyr: "draeldyn", pt: "quinta-feira", category: "calendario", notes: "sufixo -dyn (de aeldyn); abrev. DRÆ" },
    { saelthyr: "caeldyn", pt: "sexta-feira", category: "calendario", notes: "sufixo -dyn (de aeldyn); abrev. CÆL" },
    { saelthyr: "hushdyn", pt: "sábado", category: "calendario", notes: "sufixo -dyn (de aeldyn); abrev. HUS" },
    { saelthyr: "fyrnyr", pt: "janeiro", category: "calendario", notes: "sufixo -nyr (de nyrel = lua); abrev. FYR" },
    { saelthyr: "vayrnyr", pt: "fevereiro", category: "calendario", notes: "sufixo -nyr (de nyrel = lua); abrev. VAY" },
    { saelthyr: "thurnyr", pt: "março", category: "calendario", notes: "sufixo -nyr (de nyrel = lua); abrev. ÞUR" },
    { saelthyr: "draelnyr", pt: "abril", category: "calendario", notes: "sufixo -nyr (de nyrel = lua); abrev. DRÆ" },
    { saelthyr: "myrnyr", pt: "maio", category: "calendario", notes: "sufixo -nyr (de nyrel = lua); abrev. MYR" },
    { saelthyr: "nethnyr", pt: "junho", category: "calendario", notes: "sufixo -nyr (de nyrel = lua); abrev. NEÞ" },
    { saelthyr: "skaelnyr", pt: "julho", category: "calendario", notes: "sufixo -nyr (de nyrel = lua); abrev. SKÆ" },
    { saelthyr: "haevnyr", pt: "agosto", category: "calendario", notes: "sufixo -nyr (de nyrel = lua); abrev. HÆV" },
    { saelthyr: "aelnyr", pt: "setembro", category: "calendario", notes: "sufixo -nyr (de nyrel = lua); abrev. ÆLN" },
    { saelthyr: "caelnyr", pt: "outubro", category: "calendario", notes: "sufixo -nyr (de nyrel = lua); abrev. CÆL" },
    { saelthyr: "saelnyr", pt: "novembro", category: "calendario", notes: "sufixo -nyr (de nyrel = lua); abrev. SÆL" },
    { saelthyr: "cruornyr", pt: "dezembro", category: "calendario", notes: "sufixo -nyr (de nyrel = lua); abrev. CRU" },
    { saelthyr: "Zer haveth skeldra.", pt: "Eu tenho uma espada.", category: "frases" },
    { saelthyr: "Nythel essyr hir.", pt: "A noite está aqui.", category: "frases" },
    { saelthyr: "Cruorath va daemor.", pt: "Sangue de demônio.", category: "frases" },
    { saelthyr: "Fyr et skeldra.", pt: "Fogo e espada.", category: "frases" },

    /* —— Frases —— */
    { saelthyr: "Hael, kylor.", pt: "Olá, amigo.", category: "frases" },
    { saelthyr: "Zer gueth sael.", pt: "Eu guio a alma.", category: "frases" },
    { saelthyr: "Zer sereth raith va ryn.", pt: "Eu protejo o seu caminho.", category: "frases" },
    { saelthyr: "Vyrel Aelthyr; neth Preirt.", pt: "Vida em Aelthyr; morte em Preirt.", category: "frases" },
    {
      saelthyr: "Omnis sael nyreth Aelthyr, qalreth brachim Preirt.",
      pt: "Toda alma nasce sob Aelthyr e termina nos braços de Preirt.",
      category: "frases",
    },
    { saelthyr: "Naryth kel-dyreth.", pt: "Não diga o sobrenome verdadeiro.", category: "frases", notes: "Nunca pronunciar naryth em público" },
    { saelthyr: "Preirt essyr hushyr.", pt: "Preirt está em silêncio.", category: "frases" },
    { saelthyr: "Ryn essyr kylor kae?", pt: "Você é amigo?", category: "frases" },
    { saelthyr: "Zer volyth merath.", pt: "Eu quero comida.", category: "frases" },
    { saelthyr: "Ryn poth syreth zer kae?", pt: "Você pode me ajudar?", category: "frases" },
    { saelthyr: "Zer vaelth kel.", pt: "Eu não sei.", category: "frases" },
    { saelthyr: "Graeth, kylor.", pt: "Obrigado, amigo.", category: "frases" },
    { saelthyr: "Faren va hushyr.", pt: "Adeus em paz.", category: "frases" },
    { saelthyr: "Zer essyr daemor.", pt: "Eu sou um demônio.", category: "frases" },
    { saelthyr: "Nythryl essyr nex Cor Preirti.", pt: "A árvore negra está perto do Coração de Preirt.", category: "frases" },
    { saelthyr: "Thraelim qyr velth kel-essyr yn orvyn va zer vraen sevath kel-haveth dyreth, qed sy zerim volyth dyreth aelim nyth.", pt: "Coisas que não existiam no meu mundo antes do pacto não têm palavra, mesmo se nós quisermos dizê-las agora.", category: "frases" },
    { saelthyr: "Ryn velth vyth syrel va zer kae?", pt: "Você viu meu filho?", category: "frases", notes: "velth = passado antes do verbo" },
  ],
};
